ALTER TABLE queue ADD COLUMN IF NOT EXISTS parent_id UUID DEFAULT NULL REFERENCES queue(id) ON DELETE SET NULL;
ALTER TABLE flo ADD COLUMN IF NOT EXISTS queue_id UUID DEFAULT NULL REFERENCES queue(id) ON DELETE SET NULL;
