ALTER TABLE flo ADD COLUMN IF NOT EXISTS notify_on_success BOOLEAN DEFAULT FALSE;
ALTER TABLE flo ADD COLUMN IF NOT EXISTS notify_on_failure BOOLEAN DEFAULT FALSE;
ALTER TABLE flo ADD COLUMN IF NOT EXISTS notification_emails TEXT DEFAULT NULL;
